// Demo presets — Nigerian post-NYSC personas. Each preset ships with:
//  - a full `intake` payload (identical to a real form submission)
//  - a `cachedAtlasUrl` pointing to a pre-computed atlas JSON in /public/presets/
//
// When a user clicks a preset the frontend serves the cached atlas instantly
// (with a fake-streamed progress animation for feel) instead of waiting ~90s
// on a live Opus call. Regenerate the cached files by running:
//   npm run generate-presets
// See scripts/generate-presets.js for details.
export const DEMO_PRESETS = [
  {
    id: "microbio-ibadan",
    emoji: "🧫",
    title: "Microbiology grad, Ibadan",
    tagline: "1 year post-NYSC, teaching lessons, mother has diabetes",
    cachedAtlasUrl: "/presets/microbio-ibadan.json",
    intake: {
      degree: "Microbiology",
      class_of_degree: "Second Class Upper",
      university_tier: "federal",
      nysc_status: "completed",
      years_since_nysc: 1,
      state: "Oyo",
      city: "Ibadan",
      savings_ngn: 200000,
      current_monthly_income_ngn: 40000,
      current_work: "Home lesson teacher (maths + chemistry for JSS/SSS)",
      dependents: 1,
      monthly_family_obligation_ngn: 25000,
      family_pressure_level: "high",
      marital_status: "single",
      children_count: 0,
      health_constraints: "Mother has diabetes, need to be reachable within 2 hours of Ibadan",
      japa_appetite: "curious",
      risk_tolerance: "medium",
      time_horizon_months: 24,
      existing_skills: ["Teaching", "Research", "Excel"],
      hard_nos: ["Yahoo / cybercrime", "MLM / network marketing"],
    },
  },
  {
    id: "philosophy-kano",
    emoji: "📚",
    title: "Philosophy grad, Kano",
    tagline: "NYSC just ended, ₦0 savings, no clear path",
    cachedAtlasUrl: "/presets/philosophy-kano.json",
    intake: {
      degree: "Philosophy",
      class_of_degree: "Second Class Lower",
      university_tier: "federal",
      nysc_status: "completed",
      years_since_nysc: 0,
      state: "Kano",
      city: "Kano",
      savings_ngn: 0,
      current_monthly_income_ngn: 0,
      current_work: "Unemployed, living with parents",
      dependents: 0,
      monthly_family_obligation_ngn: 0,
      family_pressure_level: "medium",
      marital_status: "single",
      children_count: 0,
      japa_appetite: "curious",
      risk_tolerance: "low",
      time_horizon_months: 12,
      existing_skills: ["Writing", "Research", "Public speaking"],
      hard_nos: ["Yahoo / cybercrime"],
    },
  },
  {
    id: "masscomm-lagos",
    emoji: "🎙️",
    title: "Mass Comm grad, Lagos",
    tagline: "2 years post-NYSC, social media manager, wants remote USD",
    cachedAtlasUrl: "/presets/masscomm-lagos.json",
    intake: {
      degree: "Mass Communication",
      class_of_degree: "Second Class Upper",
      university_tier: "private",
      nysc_status: "completed",
      years_since_nysc: 2,
      state: "Lagos",
      city: "Lagos (Yaba)",
      savings_ngn: 450000,
      current_monthly_income_ngn: 150000,
      current_work: "Social media manager at a local agency",
      dependents: 0,
      monthly_family_obligation_ngn: 30000,
      family_pressure_level: "low",
      marital_status: "single",
      children_count: 0,
      japa_appetite: "committed",
      risk_tolerance: "high",
      time_horizon_months: 18,
      existing_skills: [
        "Social media management",
        "Content creation",
        "Video editing",
        "Writing",
      ],
      hard_nos: ["MLM / network marketing", "Commission-only sales"],
    },
  },
  {
    id: "accounting-abuja-married",
    emoji: "💼",
    title: "Accounting grad, married, Abuja",
    tagline: "2 yrs post-NYSC · wife in civil service · 1 toddler · JAPA-committed",
    cachedAtlasUrl: "/presets/accounting-abuja-married.json",
    intake: {
      degree: "Accounting",
      class_of_degree: "Second Class Upper",
      university_tier: "federal",
      nysc_status: "completed",
      years_since_nysc: 2,
      state: "FCT (Abuja)",
      city: "Abuja",
      savings_ngn: 1200000,
      current_monthly_income_ngn: 220000,
      current_work: "Audit associate at a tier-2 accounting firm",
      dependents: 0,
      monthly_family_obligation_ngn: 40000,
      family_pressure_level: "medium",
      marital_status: "married",
      children_count: 1,
      spouse_employment: "formal",
      spouse_monthly_income_ngn: 160000,
      japa_appetite: "committed",
      risk_tolerance: "medium",
      time_horizon_months: 24,
      existing_skills: ["Excel", "Research", "SQL", "Data entry"],
      hard_nos: ["Yahoo / cybercrime", "MLM / network marketing", "Night shifts"],
    },
  },
];
